steps:
  - label: ':docker: Build Android Gradle plugin CI image'
    key: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          build:
            - android-gradle-plugin-ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest
            - android-gradle-plugin-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-gradle-plugin-ci-v7
      - docker-compose#v3.7.0:
          push:
            - android-gradle-plugin-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-gradle-plugin-ci-v7

  - label: ':android: Detekt'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci
          command: ['./gradlew', 'detekt']

  - label: ':android: Ktlint'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci
          command: ['./gradlew', 'ktlintCheck']

  - label: ':android: Unit tests'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci
          command: ['./gradlew', 'test']
