steps:
  - label: ':docker: Build Bugsnag Gradle plugin CI image'
    key: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          build:
            - bugsnag-gradle-plugin
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest
            - bugsnag-gradle-plugin:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:bugsnag-gradle-plugin-v7
      - docker-compose#v3.7.0:
          push:
            - bugsnag-gradle-plugin:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:bugsnag-gradle-plugin-v7

  - label: ':android: Detekt'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: bugsnag-gradle-plugin
          command: ['./gradlew', 'detekt']

  - label: ':android: Ktlint'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: bugsnag-gradle-plugin
          command: ['./gradlew', 'ktlintCheck']

  - label: ':android: Unit tests'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: bugsnag-gradle-plugin
          command: ['./gradlew', 'test']

  - label: ':android: AGP 7.0.0 E2E tests'
    depends_on: 'agp-ci'
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v3.7.0:
          run: bugsnag-gradle-plugin
          env:
            - AGP_VERSION=7.0.0
            - GRADLE_WRAPPER_VERSION=7.0.2
            - RN_FIXTURE_DIR=features/fixtures/rn065/android
          command: ['bundle', 'exec', 'maze-runner', '-c', '--verbose', '--fail-fast']

  - label: ':android: AGP 7.2.0 E2E tests'
    depends_on: 'agp-ci'
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v3.7.0:
          run: bugsnag-gradle-plugin
          env:
            - AGP_VERSION=7.2.0
            - GRADLE_WRAPPER_VERSION=7.3.3
            - RN_FIXTURE_DIR=features/fixtures/rn065/android
          command: ['bundle', 'exec', 'maze-runner', '-c', '--verbose', '--fail-fast']

  - label: ':android: AGP 7.4.1 E2E tests'
    depends_on: 'agp-ci'
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v3.7.0:
          run: bugsnag-gradle-plugin
          env:
            - AGP_VERSION=7.4.1
            - GRADLE_WRAPPER_VERSION=7.5.1
            - RN_FIXTURE_DIR=features/fixtures/rn70/android
          command: ['bundle', 'exec', 'maze-runner', '-c', '--verbose', '--fail-fast']

  - label: ':android: AGP 7.2.1 R/N 0.70 E2E tests'
    depends_on: 'agp-ci'
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v3.7.0:
          run: bugsnag-gradle-plugin
          env:
            - AGP_VERSION=7.2.1
            - GRADLE_WRAPPER_VERSION=7.3.3
            - RN_FIXTURE_DIR=features/fixtures/rn70/android
          command: ['bundle', 'exec', 'maze-runner', '-c', '--verbose', '--fail-fast']
