FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/android:bugsnag-gradle-plugin as android

WORKDIR /app

# Copy gradle files
COPY gradlew gradle.properties /app/
COPY gradle/ /app/gradle/
COPY build.gradle.kts settings.gradle.kts /app/

# Copy CLI files
COPY bugsnag-cli/ bugsnag-cli/

# Copy plugin source files
COPY bugsnag-gradle-plugin/ bugsnag-gradle-plugin/

COPY scripts/ scripts/
COPY LICENSE LICENSE

CMD "scripts/docker-publish.sh"
